name: "Test / Inputs"

on:
  pull_request:
    branches:
    - main

jobs:
  test_private_key:
    name: Private Key
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./
        env:
          COBLOCKS: ${{ secrets.SETUP_SECURE_SHELL_TEST_COBLOCKS_REPO_KEY }}
        with:
          ssh-private-key: $COBLOCKS

      # Do not use this method in production, as we are only testing that the
      # private key input works for this Action. In practice, you would not use
      # this SSH tool for cloning a repo from GitHub, as that is handled
      # beautifully with @actions/checkout using the ssh-key config.
      - name: Expect to clone CoBlocks repo
        run: |
          git clone git@github.com:godaddy-wordpress/coblocks.git

  test_known_hosts_default:
    name: Known Hosts / Default
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./

      - name: Expect known_hosts to equal default input
        run: |
          DEFAULT_KNOWN_HOSTS="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
          if [[ $(cat $KNOWN_HOSTS_FILE) != "${DEFAULT_KNOWN_HOSTS}" ]]; then
            echo "KNOWN"
            cat $KNOWN_HOSTS_FILE
            echo "DEFAULT"
            echo "${DEFAULT_KNOWN_HOSTS}"
            exit 1
          fi

  test_known_hosts_empty:
    name: Known Hosts / Empty
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./
        with:
          add-gh-known-hosts: no

      - name: Expect known_hosts to be empty
        run: |
          if [[ $(cat $KNOWN_HOSTS_FILE) != "" ]]; then
            cat $KNOWN_HOSTS_FILE
            exit 1
          fi

  test_known_hosts_custom:
    name: Known Hosts / Custom
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./
        with:
          add-gh-known-hosts: no
          ssh-known-hosts: |-
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
            ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

      - name: Expect known_hosts to equal custom input
        run: |
          CUSTOM_KNOWN_HOSTS="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
          if [[ $(cat $KNOWN_HOSTS_FILE) != "${CUSTOM_KNOWN_HOSTS}" ]]; then
            echo "KNOWN"
            cat $KNOWN_HOSTS_FILE
            echo "CUSTOM"
            echo "${CUSTOM_KNOWN_HOSTS}"
            exit 1
          fi
