name: WIP Test

on:
  pull_request:
    branches:
    - main

jobs:
  test_setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: ./

      - name: Expect SSH_AGENT_PID to be present
        run: |
          [[ -z "${SSH_AGENT_PID}" ]] && exit 1 || echo $SSH_AGENT_PID
